### ISSUE TITLE
Move privacy terms, terms condition & cookie should load in its own url

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#107]
The terms and condition, cookie, as well as the privacy terms are currently shown in a modal.

We would like to host those files in a their own routes/url so that it can be linked from various places/sites.
For example, under the `http://babylonlabs.io/terms-of-use and http://babylonlabs.io/privacy-notice`.
Due to limited dev bandwidth, we can start with plain text and evolve in the future

**Comment by gbarkhatov** [comment]
@jrwbabylonlab yes in #117, footer link added in https://github.com/babylonlabs-io/simple-staking/pull/131
