### ISSUE TITLE
E2E test investigation

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#13]
The scope of this task is to investigate which e2e testing tool would best suit babylon simple-staking
Write down in a page with comparison if needed and do a quick spike with a simple test case.

e.g 
* https://playwright.dev/

**Comment by gbarkhatov** [comment]
@jrwbabylonlab yep, wanted to create an issue but found this one

**Comment by gbarkhatov** [comment]
I will create a PR today so we can start from it depending on how much we like the mock implementations

**Comment by gbarkhatov** [comment]
Yep when I clean out #77 we can close this

**Comment by gbarkhatov** [comment]
Created some issues from #77 discussion
