### ISSUE TITLE
Rethink about the Frontend versioning & release process

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#149]
1. simple-staking: stay with the current main, dev branch + a phase 2 base branch to start with, if we see issues, we make a call again.

2. btc-staking-ts: adopt the standard semantic versioning [Semantic Versioning 2.0.0](https://semver.org/), and use the tool of [GitHub - semantic-release/semantic-release: :package::rocket: Fully automated version management and package publishing](https://github.com/semantic-release/semantic-release)

The scope of this ticket is to make sure the above setups are completed

Note that you may need to ping devops to make sure the current auto PR creation will still work from main into the dev&phase-2 branches

**Comment by jeremy-babylonlabs** [comment]
main -> dev
dev -> phase 2
