### ISSUE TITLE
Uncaught error handling

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#158]
In our simple-staking dApp, we use an error modal to handle caught errors, but unhandled errors are not addressed properly. Currently, the dApp crashes and displays a black screen.

Ideally, we should display a proper error page that provides information about the error and offers users a way to report the issue.

See blow UX design:

5XX
![Image](https://github.com/user-attachments/assets/64901ed4-0d24-44db-b6eb-e4b0061a0410)
![Image](https://github.com/user-attachments/assets/21ba4df6-80f9-4de6-9d6b-f94ad9ca4e9e)

404:
![Image](https://github.com/user-attachments/assets/c732418b-62e6-48d8-8926-4bef76c32915)

**Comment by totraev** [comment]
> @totraev what do you think about ErrorBoundaries?

We definitely need add them

**Comment by totraev** [comment]
By the way, why we decided to use modals? Why just not use toasts like this one? https://react-hot-toast.com/ Any concerns? @gbarkhatov @jrwbabylonlab

**Comment by gbarkhatov** [comment]
@totraev It was discussed that way, for us to have modals describing the stuff. With cancel/try again buttons, which are not that suited for the Toasts
