### ISSUE TITLE
Port new wallets into wallet connect

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#184]
At the time of wallet connect was being built/integrated into dApp. there were some new wallets being added
- casctus linnk
- ...

Please refer to https://docs.tomo.inc/tomo-sdk/tomo-connect-sdk-lite#submit-wallet-pr for backporting the missing provider

**Comment by gbarkhatov** [comment]
@jrwbabylonlab I suggest closing this ticket given that we have another way (separate lib with separate kind of problems).
I will create needed tickets on https://github.com/babylonlabs-io/bbn-wallet-connect repo
