### ISSUE TITLE
Submit signed staking tx to BTC

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#190]
Blocked by https://github.com/babylonlabs-io/btc-staking-ts/issues/32 and https://github.com/babylonlabs-io/simple-staking/issues/219#issue-2581323243

The scope of this ticket is:
- Able to show "stake" button on a verified delegation
- upon the click of "stake" button, trigger the sign of staking tx psbt
- submit to BTC node
- Post a status update request to backend service with state of "pending-btc-confirmation"

Reference: https://babylonlabs.atlassian.net/wiki/spaces/BABYLON/pages/37978829/User+dataflow+within+FE+BE#Stakes

**Comment by gbarkhatov** [comment]
>Post a status update request to backend service with state of "pending-btc-confirmation"

Not needed right now
