### ISSUE TITLE
Offer staker option to filter ordinals

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#207]
Instead of always attempting to filter staker ordinals automatically, we should offer a different approach where stakers can choose whether to include or exclude UTXOs with ordinals.

The process would work as follows:
- The user connects their wallet, and we check against the ordinal service.
- If ordinals are found, we display a message asking the user to confirm whether they want to include the UTXO or filter it out from the staking balance.
- By default (in case backend never respond or returned error) we exclude the UTXOs with ordinals
       

https://www.figma.com/design/EbglGlHvz6C8AZpzijQFc6/Sandbox?node-id=46-14538&t=0BAQJe1GP9UeR0CN-1 

The text of the checkbox at wallet connect modal shall be updated. please ask legal team about the exact wordings

**NOTE: You should raise PR against main**

**Comment by gbarkhatov** [comment]
Closed in #251
