### ISSUE TITLE
Improve finality provider list

### ISSUE THREAD

**Issue by totraev** [babylonlabs-io/simple-staking#216]
Add new col [`status`](https://babylonlabs.atlassian.net/wiki/spaces/BABYLON/pages/41877853/Phase-2+UI+Components#4.1-Finality-Provider-list) + add possibility to sort by name, by total delegations and by commission rate.

Additional refactoring steps:

1. Wrap up usInfinityQuery for FP into custom hook `useFinalityProviders` and move it inside `useFinalityProviderData`
2. Rename `useFinalityProviderData` to `useFinalityProviderService`

**Comment by jeremy-babylonlabs** [comment]
> @jeremy-babylonlabs please correct me if i'm wrong. the api will also support querying with the sorting mentioned in description, right?

Yes that's correct
