### ISSUE TITLE
Split ticket for FE to adopt endpoint instead of using mocked data

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#277]
The backend should have most of endpoints served with real data.
Let's move forward with adopting those endpoint in the FE so that we can see the delegations coming through

- [x] #297
- [x] #298
- [x] #299
- [x] #300
- [x] #301

**Comment by jeremy-babylonlabs** [comment]
- [ ] adopt params endpoint
- [ ] adopt fp endpoint
- [ ] adopt delegation endpoint
- [ ] adopt staker stats endpoint
- [ ] adopt stats endpoint
