### ISSUE TITLE
Investigate if BTC staking tx fee can be fixed

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#345]
In our pre-approval flow, we submit an EOI (Expression of Interest) where the staking transaction within the EOI already has its fees calculated based on the current fee rate.

However, there’s a small time gap between the creation of the EOI and when the user actually stakes. This means that the staking transaction is subject to changes in the fee rate, which could result in a mismatch of tx hash. In other words, the staking transaction generated at the time of EOI creation may no longer match the transaction that should be submitted to the BTC network at staking time.
**Even worse, if user decide to do custom fee rate, then our dApp lose track of the fee for the transaction because there is no where we can get this piece of data upon user page reload**

High-Level Options:

Option 1:
	1.	When creating the EOI staking transaction, we calculate the total fees needed based on the initial fee rate.
	2.	When BBN receives the EOI along with the staking transaction, it derives the expected fee for this staking transaction.
	3.	This fee is then emitted as part of the delegation event.
	4.	The frontend will consume this fee and submit the transaction with the provided fee, without recalculating based on the latest fee rate.

Option 2:
	•	When submitting the EOI, BBN accepts an additional field, feeRate, specifically for the staking transaction.
	•	BBN validates the provided fee rate by calculating based on the staking amount, dust, etc., ensuring it’s legitimate.
	•	This feeRate is emitted as part of the delegation event.
	•	The frontend will consume this feeRate directly instead of using the “real-time fee rate” from the mempool when submitting the staking transaction.

Option 3: BBN to emit the staking tx hex. dApp will use the input&output from this unsigned Tx to create psbt and ask staker to sign and submit. 

**Preferred option 3 -> option 2 -> option 1**

**Comment by gitferry** [comment]
Option 3 sounds good to me. In happy path, the time gap is fairly small (in seconds), it should be OK to use the tx hex emitted from Babylon. In unhappy path where the free rate varies much during Babylon execution, the user may need to resubmit another eoi. Either way, the user needs to stick with the tx in the eoi and cannot use rbf. Otherwise, a new eoi should be submitted
