### ISSUE TITLE
[UI] Finality provider list

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#351]
![Image](https://github.com/user-attachments/assets/5530efc9-3d19-4bb6-a6c2-4a466ba1ca75)

The scope of the ticket does not include searching and sorting, but include the right hand filter which have:
1. Show active
2. Show Inactive
does not include the "pending transition"

If No matches found, show below
![Image](https://github.com/user-attachments/assets/f1bb4c81-44ca-4535-bbe8-0a40c745f71f)

**Comment by jeremy-babylonlabs** [comment]
related PR: https://github.com/babylonlabs-io/bbn-core-ui/pull/50
