### ISSUE TITLE
[UI] FAQ

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#362]
![Image](https://github.com/user-attachments/assets/c2813df7-722d-4c75-b8f3-e79fb5c2c5ba)

The scope of this ticket include:
- Add the relevant component into design system (e.g Accordion)
- Adopt it in the simple-staking

**Comment by supertong** [comment]
https://github.com/babylonlabs-io/simple-staking/pull/381
