### ISSUE TITLE
Retrieve wallet balance

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#386]
Note: This ticket is not about rebranding.

For the wallet balance section, we are currently using the mocked data.
Try retrieve the relevant data from BTC & BBN wallet to display.

![Image](https://github.com/user-attachments/assets/c2a19358-b508-49cc-9b36-9b8d738b8f88)

You do not need to populate the data for the rewards part. This will be done by other tasks. i.e #372

**Comment by Andesxtzgerald** [comment]
> Note: This ticket is not about rebranding.
> 
> For the wallet balance section, we are currently using the mocked data. Try retrieve the relevant data from BTC & BBN wallet to display.
> 
> ![Image](https://private-user-images.githubusercontent.com/154598612/389746065-c2a19358-b508-49cc-9b36-9b8d738b8f88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODcxMTksIm5iZiI6MTczMjU4NjgxOSwicGF0aCI6Ii8xNTQ1OTg2MTIvMzg5NzQ2MDY1LWMyYTE5MzU4LWI1MDgtNDljYy05YjM2LTliOGQ3MzhiOGY4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMjA2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDRjNWQ2ZDEzY2ZhMzJhOWNiMDg4YzA0OGY0MWRiZmY5ZWRlOTA5NjFjM2I4YTk4Y2RiZGYzOGZiZjEzNjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5FhnTkisiR0BWL3getg7-IQIO1bd_rTYsHUAuGEr90E)
> 
> You do not need to populate the data for the rewards part. This will be done by other tasks. i.e #372


Hello @jrwbabylonlab 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID BTC12638
Please see the link below to our dedicated support line:
[Bitcoin Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
