### ISSUE TITLE
[UI] Error modal to follow rebranding

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#428]
The Error modal is still with the old design.
E.g
![Image](https://github.com/user-attachments/assets/e004f8aa-2462-4585-84fa-fb4bdca2aabd)

Update it to follow the new rebranding design

Ping Dan is unable to find it in figma

**Comment by supertong** [comment]
Looks like it's resolved now?
![Image](https://github.com/user-attachments/assets/f52aa416-3ed1-4ead-ab69-ea14efc739d1)
