### ISSUE TITLE
[UI] Staking Info modal

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#445]
![Image](https://github.com/user-attachments/assets/27e5e356-aa09-4135-ae49-90998eb8fd8f)

Upon clicking the "Learn more" should take us to below

![Image](https://github.com/user-attachments/assets/e3b17e8f-9c79-4e3b-b386-295286700280)

**Comment by supertong** [comment]
https://github.com/babylonlabs-io/simple-staking/pull/471
