### ISSUE TITLE
[UI] Show staking disabled is still within the allowList timewindow

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#458]
![Image](https://github.com/user-attachments/assets/5e61286f-cc4b-4d37-9bb8-eb6e48776bd9)

This shall be determined by the response from backend API `network-status` endpoint

Use the 
```
"staking_status": {
            "is_staking_open": true
        },
```

value to determine whether the form shall be disabled and above should be shown.

NOTE: Due to bandwidth concern, adding the timestamp here will be quite complex(time consuming), i would leave it as "Staking is not enabled at this time. Please check back later". But of course, something we will continue look into after testnet as improvement

**Comment by supertong** [comment]
https://github.com/babylonlabs-io/simple-staking/pull/542
