### ISSUE TITLE
Update wallets icon file

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/simple-staking#6]
- Bitget wallet icon is ~3.7mb svg, we should replace it with a proper minified svg file
- Tomo wallet has new logo: https://i.imgur.com/KsFqIoe.png
Source: https://tomo.inc/images/logo.svg (cut the left part)

**Comment by vitsalis** [comment]
@gbarkhatov closed by #17 ?

**Comment by gbarkhatov** [comment]
Closed by #17
